FROM node:20

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

COPY .env .env

ENV ACCESS_TOKEN_SECRET_KEY=${ACCESS_TOKEN_SECRET_KEY}
ENV REFRESH_TOKEN_SECRET_KEY=${REFRESH_TOKEN_SECRET_KEY}
ENV PORT=${PORT}
ENV DEFAULT_USER_EMAIL=${DEFAULT_USER_EMAIL}
ENV DEFAULT_USER_PASSWORD=${DEFAULT_USER_PASSWORD}
ENV DATABASE_URL=${DATABASE_URL}

EXPOSE ${PORT}

CMD ["npm", "start"]
